version: "3.7"
services:
  cake-manager-client:
    build:
      context: ./cake-manager-client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  cake-manager-service:
    build:
      context: ./cake-manager-service
      dockerfile: Dockerfile
    ports:
      - "8282:8080"